empresas/urls.py
from django.urls import path
from . import views

app_name = 'empresas'

urlpatterns = [
    path('', views.EmpresaListView.as_view(), name='empresa_list'),
    path('<int:pk>/', views.EmpresaDetailView.as_view(), name='detalhe'),
    path('novo/', views.EmpresaCreateView.as_view(), name='novo'),
    path('<int:pk>/editar/', views.EmpresaUpdateView.as_view(), name='editar'),
]

gams/urls.py
from django.urls import path
from . import views

app_name = 'gams'

urlpatterns = [
    path('', views.GAMListView.as_view(), name='gam_list'),
    path('<int:pk>/', views.GAMDetailView.as_view(), name='detalhe'),
    path('novo/', views.GAMCreateView.as_view(), name='novo'),
    path('<int:pk>/editar/', views.GAMUpdateView.as_view(), name='editar'),
]

genesisdev/urls.py
from django.contrib import admin

from django.urls import path

from django.urls import include, path
from projetos.views import DashboardView

from django.conf import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('ambientes/', include(('ambientes.urls', 'ambientes'), namespace='ambientes')),
    path('empresas/', include(('empresas.urls', 'empresas'), namespace='empresas')),
    path('projetos/', include(('projetos.urls', 'projetos'), namespace='projetos')),
    path('bancodedados/', include(('bancodedados.urls', 'bancodedados'), namespace='bancodedados')),
    path('webs/', include(('webs.urls', 'webs'), namespace='webs')),
    path('gams/', include(('gams.urls', 'gams'), namespace='gams')),
    path('loggenexus/', include(('loggenexus.urls', 'loggenexus'), namespace='loggenexus')),
    path('genexus/', include(('genexus.urls', 'genexus'), namespace='genexus')),
    path('credenciais/', include(('credenciais.urls', 'credenciais'), namespace='credenciais')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, "static"))
    urlpatterns += static('/admin-interface/', document_root=os.path.join(settings.BASE_DIR, "admin-interface"))

genexus/urls.py
from django.urls import path
from . import views

app_name = 'genexus'

urlpatterns = [
    path('', views.GenexusListView.as_view(), name='genexus_list'),
    path('<int:pk>/', views.GenexusDetailView.as_view(), name='detalhe'),
    path('novo/', views.GenexusCreateView.as_view(), name='novo'),
    path('<int:pk>/editar/', views.GenexusUpdateView.as_view(), name='editar'),
]

projetos/urls.py
from django.urls import path
from . import views

app_name = 'projetos'

urlpatterns = [
    path('', views.ProjetoListView.as_view(), name='projeto_list'),
    path('<int:pk>/', views.ProjetoDetailView.as_view(), name='detalhe'),
    path('novo/', views.ProjetoCreateView.as_view(), name='novo'),
    path('<int:pk>/editar/', views.ProjetoUpdateView.as_view(), name='editar'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
]

webs/urls.py
from django.urls import path
from . import views

app_name = 'webs'

urlpatterns = [
    path('', views.WebListView.as_view(), name='web_list'),
    path('<int:pk>/', views.WebDetailView.as_view(), name='detalhe'),
    path('novo/', views.WebCreateView.as_view(), name='novo'),
    path('<int:pk>/editar/', views.WebUpdateView.as_view(), name='editar'),
]

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Dashboard de Configurações</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Config Manager</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'empresas:empresa_list' %}">Empresas</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'ambientes:ambiente_list' %}">Ambientes</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'projetos:projeto_list' %}">Projetos</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'bancodedados:bancodedados_list' %}">Bancos de Dados</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'webs:web_list' %}">Webs</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'gams:gam_list' %}">GAMs</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'loggenexus:loggenexus_list' %}">LogGenexus</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'genexus:genexus_list' %}">Genexus</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'credenciais:credencial_list' %}">Credenciais</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>